version: "3.9"

networks:
  clients:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
  servers:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.11.0/24

volumes:
  server-data:
  server-storage:

services:
  router:
    image: router-image
    container_name: router
    networks:
      clients:
        ipv4_address: 10.0.10.254
      servers:
        ipv4_address: 10.0.11.254
    ports:
      - "80:80"  # Ejemplo: expone el puerto 80 para el enrutador
    privileged: true

  server:
    image: server-image
    container_name: server
    networks:
      servers:
        ipv4_address: 10.0.11.10
    volumes:
      - ./Server/data.json:/app/Server/data.json
      - server-storage:/app/Server/Storage
    ports:
      - "5000:5000"  # Expone el puerto 5000 para el servidor

  client1:
    image: client-image
    container_name: client1
    networks:
      clients:
        ipv4_address: 10.0.10.11

  client2:
    image: client-image
    container_name: client2
    networks:
      clients:
        ipv4_address: 10.0.10.12

  client3:
    image: client-image
    container_name: client3
    networks:
      clients:
        ipv4_address: 10.0.10.13
