# Operation codes in ChordNode
FIND_PREDECESSOR = 1
FIND_SUCCESSOR = 2
GET_SUCCESSOR = 3
GET_PREDECESSOR = 4
NOTIFY = 5
REVERSE_NOTIFY = 6
NOT_ALONE_NOTIFY = 7
CHECK_NODE = 8
LOOKUP = 9

# Operations in Database
ADD_FILES_TO_TAG = 10
ADD_TAGS_TO_FILE = 11
GET_FILES_FROM_TAG=12

